### ISSUE TITLE
Recording RETS API responses as fixtures

### ISSUE THREAD

**Issue by lgomez** [retsr/rets.js#16]
Been reading this: https://orchestrate.io/blog/2014/06/13/how-to-test-code-that-uses-http-apis-using-node-js-mocha-and-nock/ and thought perhaps it'd be a good idea to facilitate doing this automatically for provider-specific testing. Not necessary right now but worth the read. Let me know what you think.

**Comment by dermidgen** [comment]
Since we've adopted nock, I think it's worth exploring nock recording more deeply to create reliable fixtures that we can redact/filter sensitive response data from. It would also be nice to provide a mechanism within our tests that allows developers to hit their own servers with the same tests and record responses as fixtures for future tests.

**Comment by dermidgen** [comment]
This discussion is loosely related to PR #18
